import test from 'node:test';
import assert from 'node:assert/strict';
import { parseGcode, bboxFromGcode } from '../server/services/gcode.js';

test('parses Prusa headers', () => {
  const parsed = parseGcode('; generated by PrusaSlicer\n; filament used [g] = 12.4\n; filament used [cm3] = 10.0\n; estimated printing time = 1h 24m 0s\n; layer_height = 0.2\n; nozzle_diameter = 0.4');
  assert.equal(parsed.weightG, 12.4);
  assert.equal(parsed.printTimeSec, 5040);
  assert.equal(parsed.confidence, 'header');
});

test('parses Cura and Bambu variants', () => {
  let parsed = parseGcode(';Generated with Cura\n;Filament used: 7.2g\n;TIME:600');
  assert.equal(parsed.weightG, 7.2);
  assert.equal(parsed.printTimeSec, 600);

  parsed = parseGcode('; Bambu Studio\n; filament_weight = 9\n; estimated time = 2m');
  assert.equal(parsed.confidence, 'header');
});

test('missing metadata is not trusted', () => assert.equal(parseGcode('G1 X1 E1').confidence, null));

test('parses Bambu and Prusa production headers', () => {
  const parsed = parseGcode('; total filament used [g] = 31.72\n; estimated printing time (normal mode) = 2h 16m 8s\n; filament_type = PETG');
  assert.equal(parsed.weightG, 31.72);
  assert.equal(parsed.printTimeSec, 8168);
  assert.equal(parsed.metadata.filamentType, 'PETG');
});

test('parses Bambu HEADER_BLOCK fields', () => {
  const parsed = parseGcode(`; HEADER_BLOCK_START
; BambuStudio 02.02.01.60
; model printing time: 49m 2s; total estimated time: 55m 18s
; total layer number: 200
; total filament length [mm] : 5729.02
; total filament volume [cm^3] : 13.78
; total filament weight [g] : 17.50
; filament_density: 1.27
; filament_diameter: 1.75
; max_z_height: 40.00
; HEADER_BLOCK_END
; CONFIG_BLOCK_START
; printer_model = Bambu Lab P1S
; filament_type = PETG
; layer_height = 0.2
; nozzle_diameter = 0.4
; CONFIG_BLOCK_END
G1 X10 Y10 Z0.2 E1
G1 X50 Y50 Z40 E2`);

  assert.equal(parsed.weightG, 17.5);
  assert.equal(parsed.filamentLengthMm, 5729.02);
  assert.equal(parsed.printTimeSec, 3318);
  assert.equal(parsed.metadata.maxZHeightMm, 40);
  assert.equal(parsed.metadata.layerCount, 200);
  assert.equal(parsed.metadata.printerModel, 'Bambu Lab P1S');
  assert.equal(parsed.metadata.filamentType, 'PETG');
  assert.equal(parsed.metadata.layerHeightMm, 0.2);
  assert.equal(parsed.confidence, 'header');
  assert.equal(parsed.bboxMm.x, 40);
  assert.equal(parsed.bboxMm.y, 40);
});

test('derives bbox from extruding gcode moves only', () => {
  const bbox = bboxFromGcode([
    'G90',
    'M82',
    'G1 X0 Y0 Z0 F3000',
    'G1 X250 Y250 Z0 F9000',
    'G1 X0 Y0 Z0.2 E1',
    'G1 X20 Y30 Z10 E2',
    'G1 X5 Y15 Z2 E3'
  ].join('\n'));
  assert.equal(bbox.x, 20);
  assert.equal(bbox.y, 30);
  assert.equal(Number(bbox.z.toFixed(1)), 9.8);
});

test('prefers header max_z_height for model size Z', () => {
  const parsed = parseGcode(`; HEADER_BLOCK_START
; max_z_height: 15.00
; total filament weight [g] : 12.33
; total estimated time: 23m 4s
; HEADER_BLOCK_END
G90
M82
G1 X0 Y0 Z0.2 E1
G1 X20 Y12 Z0.2 E2
G1 X20 Y12 Z50 E3
`);
  assert.equal(parsed.bboxMm.x, 20);
  assert.equal(parsed.bboxMm.y, 12);
  assert.equal(parsed.bboxMm.z, 15);
});

test('parses Bambu times that include days', () => {
  const parsed = parseGcode(`; HEADER_BLOCK_START
; model printing time: 1d 9h 32m 37s; total estimated time: 1d 9h 39m 31s
; total filament weight [g] : 838.52
; HEADER_BLOCK_END`);
  assert.equal(parsed.weightG, 838.52);
  assert.equal(parsed.printTimeSec, 1 * 86400 + 9 * 3600 + 39 * 60 + 31);
  assert.equal(parsed.confidence, 'header');
});

test('reads PrusaSlicer filament stats from the file footer', () => {
  const filler = Array.from({ length: 3000 }, (_, i) => `G1 X${i} Y0 E${i * 0.01}`).join('\n');
  const parsed = parseGcode(`; generated by PrusaSlicer 2.9.0\n${filler}
; filament used [mm] = 19843.70
; filament used [cm3] = 47.73
; filament used [g] = 59.18
; total filament used [g] = 59.18
; estimated printing time (normal mode) = 5h 12m 51s
`);
  assert.equal(parsed.weightG, 59.18);
  assert.equal(parsed.printTimeSec, 5 * 3600 + 12 * 60 + 51);
  assert.equal(parsed.confidence, 'header');
});
