# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aa93d62f6b00d7d94e9b37822ca7399a"
name = "3DNow Quote Engine"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_orders,write_webhooks,read_webhooks"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
